from types import SimpleNamespace

Config = SimpleNamespace(
    MONO_FONTS=["monospace"],
    SANS_FONTS=[
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
    ],
    MODEL="Lykon/dreamshaper-8",
    MODELS=[
        "fluently/Fluently-v4",
        "Linaqruf/anything-v3-1",
        "Lykon/dreamshaper-8",
        "prompthero/openjourney-v4",
        "runwayml/stable-diffusion-v1-5",
        "SG161222/Realistic_Vision_V5.1_Novae",
    ],
    SCHEDULER="DEIS 2M",
    SCHEDULERS=[
        "DDIM",
        "DEIS 2M",
        "DPM++ 2M",
        "Euler",
        "Euler a",
        "PNDM",
    ],
    EMBEDDING="fast_negative",
    EMBEDDINGS={
        "bad_dream",
        "fast_negative",
        "unrealistic_dream",
    },
    STYLE="sai-enhance",
    WIDTH=448,
    HEIGHT=576,
    NUM_IMAGES=1,
    SEED=-1,
    GUIDANCE_SCALE=6,
    INFERENCE_STEPS=35,
    DENOISING_STRENGTH=0.6,
    DEEPCACHE_INTERVAL=2,
    SCALE=1,
    SCALES=[1, 2, 4],
)
